name: eiga
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  isar_community: ^3.3.1
  isar_community_flutter_libs: ^3.3.2
  hooks_riverpod: ^2.6.1
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  file_picker: ^10.3.10
  video_player: ^2.11.1
  flick_video_player: ^0.9.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_community_generator: ^3.3.2
flutter:
  uses-material-design: true

